#!/usr/bin/env bash
# Start the fLEET admin panel (Phoenix) in production mode.
#
#   bash admin/prod-start.sh [--host HOST] [--port PORT]
#
# Runs the panel with MIX_ENV=prod: minified + digested static assets,
# force_ssl/HSTS, logger :info. Prefer this over admin/start.sh (dev) for any
# non-local deployment.
#
# Unlike the dev script, no local placeholder tokens are invented here. Secrets
# are read from the git-ignored ../secrets.env (and can be overridden by the
# environment). The following are required or defaulted:
#
#   SECRET_KEY_BASE  Phoenix secret. If unset, one is generated once and
#                    appended to ../secrets.env so restarts keep the same key.
#   DATABASE_PATH    SQLite file path. Defaults to <repo>/fleet_admin_prod.db.
#   PHX_HOST         Public host. Defaults to the host of FLEET_INGEST_PUBLIC_URL,
#                    otherwise "localhost".
#   PORT             HTTP port (default 4000). The bind address follows
#                    config/prod.exs (all interfaces; set PHX_IP to override is
#                    not supported — edit config/prod.exs if you must).
set -euo pipefail

cd "$(dirname "$0")"
ADMIN_DIR="$(pwd)"
ROOT_DIR="$(cd .. && pwd)"
SECRETS_FILE="$ROOT_DIR/secrets.env"

# Load local runtime secrets so restarts keep the real values. An explicitly
# set environment variable always wins.
if [ -f "$SECRETS_FILE" ]; then
  set -a
  # shellcheck disable=SC1091
  . "$SECRETS_FILE"
  set +a
fi

HOST="${PHX_IP:-0.0.0.0}"
PORT="${PORT:-4000}"

usage() {
  cat <<'EOF'
Start the fLEET admin panel in production mode.

  bash admin/prod-start.sh [--host HOST] [--port PORT]

Defaults:
  --host  0.0.0.0 (informational; bind is governed by config/prod.exs)
  --port  4000
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --host)         HOST="${2:?--host requires a value}"; shift 2 ;;
    --host=*)       HOST="${1#*=}"; shift ;;
    --port)         PORT="${2:?--port requires a value}"; shift 2 ;;
    --port=*)       PORT="${1#*=}"; shift ;;
    -h|--help)      usage; exit 0 ;;
    *) echo "unknown argument: $1" >&2; usage >&2; exit 2 ;;
  esac
done

export MIX_ENV=prod
export PORT="$PORT"

# --- SECRET_KEY_BASE ---------------------------------------------------------
# Generate a stable key once and persist it so cookie/session signing survives
# restarts. Never committed: secrets.env is git-ignored.
if [ -z "${SECRET_KEY_BASE:-}" ]; then
  SECRET_KEY_BASE="$(mise exec -- mix phx.gen.secret)"
  printf '\n# Generated by admin/prod-start.sh for production mode.\nSECRET_KEY_BASE=%s\n' "$SECRET_KEY_BASE" >> "$SECRETS_FILE"
  echo "[prod] generated SECRET_KEY_BASE and stored it in $SECRETS_FILE"
  export SECRET_KEY_BASE
fi

# --- DATABASE_PATH -----------------------------------------------------------
# Relative paths are resolved against the admin dir; default to the repo root
# (git-ignored via *.db). An explicitly empty value is treated as unset.
if [ -z "${DATABASE_PATH:-}" ]; then
  DATABASE_PATH="$ROOT_DIR/fleet_admin_prod.db"
  export DATABASE_PATH
fi

# --- PHX_HOST ----------------------------------------------------------------
if [ -z "${PHX_HOST:-}" ]; then
  if [ -n "${FLEET_INGEST_PUBLIC_URL:-}" ]; then
    # Strip scheme + path: https://dotfleet.mikrus.dev/api/ingest -> dotfleet.mikrus.dev
    PHX_HOST="$(printf '%s' "$FLEET_INGEST_PUBLIC_URL" | sed -E 's#^[a-zA-Z][a-zA-Z0-9+.-]*://##; s#/.*$##')"
  else
    PHX_HOST="localhost"
  fi
  export PHX_HOST
fi

# --- Dependencies ------------------------------------------------------------
if [ ! -d deps/phoenix ]; then
  echo "[prod] fetching dependencies"
  mise exec -- mix deps.get --only prod
fi

# --- Assets ------------------------------------------------------------------
# assets.deploy needs the colocated CSS that only exists after a prod compile,
# and the digest manifest only needs rebuilding when the source changed. Skip
# the rebuild when a manifest is already present; delete it to force.
if [ ! -f priv/static/cache_manifest.json ]; then
  echo "[prod] compiling"
  mise exec -- mix compile
  echo "[prod] building minified + digested assets"
  mise exec -- mix assets.deploy
fi

# --- Database ----------------------------------------------------------------
echo "[prod] ensuring database is migrated"
mise exec -- mix ecto.create --quiet >/dev/null 2>&1 || true
mise exec -- mix ecto.migrate --quiet

# --- Safety warning ----------------------------------------------------------
case "$HOST" in
  127.0.0.1 | localhost | ::1) ;;
  *)
    if [ -z "${FLEET_ADMIN_PASSWORD:-}" ]; then
      echo "[prod] WARNING: no FLEET_ADMIN_PASSWORD set — the admin UI is unauthenticated" >&2
    fi
    ;;
esac

echo "[prod] fLEET admin panel (production): http://${HOST}:${PORT}"
echo "[prod] host:            ${PHX_HOST}"
echo "[prod] database:        ${DATABASE_PATH}"
echo "[prod] ingest token:    ${FLEET_INGEST_TOKEN:+<set>}${FLEET_INGEST_TOKEN:-<open, no auth>}"
echo "[prod] admin auth:      ${FLEET_ADMIN_USER:+<set>}${FLEET_ADMIN_USER:-<disabled>}"

exec mise exec -- mix phx.server
